echo "Started deployment script ..."
echo -p $SERVER_PASSWORD scp -r $RELEASE_DIR_ON_RUNNER/$FILE_NAME $SERVER_USER@$SERVER_HOST:$DIR_ON_TARGET_SERVER/new_$FILE_NAME
sshpass -p $SERVER_PASSWORD scp -r $RELEASE_DIR_ON_RUNNER/$FILE_NAME $SERVER_USER@$SERVER_HOST:$DIR_ON_TARGET_SERVER/new_$FILE_NAME


echo -p $SERVER_PASSWORD scp -r $DEPLOY_SCRIPT_DIR/$BACKUP_SCRIPT $SERVER_USER@$SERVER_HOST:$DIR_ON_TARGET_SERVER/$BACKUP_SCRIPT
sshpass -p $SERVER_PASSWORD scp -r $DEPLOY_SCRIPT_DIR/$BACKUP_SCRIPT $SERVER_USER@$SERVER_HOST:$DIR_ON_TARGET_SERVER/$BACKUP_SCRIPT

echo "Running backup script ..."
echo -p $SERVER_PASSWORD ssh $SERVER_USER@$SERVER_HOST $DIR_ON_TARGET_SERVER && $BACKUP_SCRIPT
sshpass -p $SERVER_PASSWORD ssh $SERVER_USER@$SERVER_HOST $DIR_ON_TARGET_SERVER && $BACKUP_SCRIPT
echo "End of script ..."