name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Archive WAR file
      uses: actions/upload-artifact@v2
      with:
        name: my-war-file
        path: target/*.war

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Upload WAR file to EC2
        run: |
          scp -i $SSH_AUTH_SOCK -o StrictHostKeyChecking=no target/*.war Administrator@${{ secrets.EC2_INSTANCE_IP }}:/C:/path/to/tomcat/webapps/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_IP }}

      #- name: Restart Tomcat on EC2
      #  run: |
      #    ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@<EC2_INSTANCE_IP> 'powershell.exe -Command "Restart-Service -Name tomcat"'
      #  env:
      #    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #    EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_IP }}